language: node_js
node_js:
  - '10'
  - '8'


cache:
  directories:
    - $HOME/.npm

install:
  - npm ci

deploy:
  on:
    branch: master
    node: '10'
  provider: npm
  email: gurpreetatwal@users.noreply.github.com
  api_key: $NPM_TOKEN
